### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ZaddikDev** [tikstock/tiktok-app-api#24]
(node:9756) UnhandledPromiseRejectionWarning: Error: Could not sign an API URL. This usually means the signature service is not responding. If you are using the default signature service, create a pull request at https://github.com/tikstock/tiktok-app-api stating this issue.
    at Object.<anonymous> (D:\Bots\PhoBot\node_modules\tiktok-app-api\dist\utility.js:63:19)
    at Generator.throw (<anonymous>)
    at rejected (D:\Bots\PhoBot\node_modules\tiktok-app-api\dist\utility.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Garoika** [comment]
Да да

**Comment by adotdaniel** [comment]
i have code to sign requests. also for comments. contact me at xgorgon@protonmail.com or telegram @adotdaniel

**Comment by Garoika** [comment]
+
